export const content = {
  grandPrix: [
    {
      name: "Sakhir GP",
      date: "2024-02-23",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Bahrain%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/bahrain-flag",
    },
    {
      name: "Bahrain GP",
      date: "2024-03-02",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Bahrain%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/bahrain-flag",
    },
    {
      name: "Saudi Arabia GP",
      date: "2024-03-09",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Saudi%20Arabia%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/saudi-arabia-flag",
    },
    {
      name: "Australia GP",
      date: "2024-03-24",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Australia%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/australia-flag",
    },
    {
      name: "Japan GP",
      date: "2024-04-07",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Japan%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/japan-flag",
    },
    {
      name: "China GP",
      date: "2024-04-21",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/China%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/china-flag",
    },
    {
      name: "Miami GP",
      date: "2024-05-05",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Miami%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/united-states-of-america-flag",
    },
    {
      name: "Emilia-Romagna GP",
      date: "2024-05-19",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Emilia%20Romagna%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/italy-flag",
    },
    {
      name: "Monaco GP",
      date: "2024-05-26",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1200,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Monte%20Carlo%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/monaco-flag",
    },
    {
      name: "Canada GP",
      date: "2024-06-09",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Canada%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/canada-flag",
    },
    {
      name: "Spain GP",
      date: "2024-06-23",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Spain%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/spain-flag",
    },
    {
      name: "Austria GP",
      date: "2024-06-30",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Austria%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag",
    },
    {
      name: "Great Britain GP",
      date: "2024-07-07",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/united-kingdom-flag",
    },
    {
      name: "Hungary GP",
      date: "2024-07-21",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Hungar%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/hungary-flag",
    },
    {
      name: "Belgium GP",
      date: "2024-07-28",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Belgium%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/belgium-flag",
    },
    {
      name: "Netherlands GP",
      date: "2024-08-25",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Netherlands%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/netherlands-flag",
    },
    {
      name: "Italy GP",
      date: "2024-09-01",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Italy%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/italy-flag",
    },
    {
      name: "Azerbaijan GP",
      date: "2024-09-15",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Azerbaijan%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/azerbaijan-flag",
    },
    {
      name: "Singapore GP",
      date: "2024-09-22",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Singapore%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/singapore-flag",
    },
    {
      name: "United States GP",
      date: "2024-10-20",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/USA%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/united-states-of-america-flag",
    },
    {
      name: "Mexico GP",
      date: "2024-10-27",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Mexico%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/mexico-flag",
    },
    {
      name: "Brazil GP",
      date: "2024-11-03",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Brazil%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/brazil-flag",
    },
    {
      name: "Las Vegas GP",
      date: "2024-11-23",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Las%20Vegas%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/united-states-of-america-flag",
    },
    {
      name: "Qatar GP",
      date: "2024-12-01",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Qatar%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1000/content/dam/fom-website/2018-redesign-assets/Flags 16x9/qatar-flag",
    },
    {
      name: "Abu Dhabi GP",
      date: "2024-12-08",
      circuit: "https://media.formula1.com/image/upload/f_auto,c_limit,w_1440,q_auto/f_auto/q_auto/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Abu%20Dhab%20carbon",
      thumbnail: "",
      flag: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/united-arab-emirates-flag",
    },
  ],
};
